version: '2'
services:
    mysql:
        build: mysql
        environment:
            - TIMEZONE=UTC
            - MYSQL_PORT=1024
        ports:
            - 127.0.0.1:1024:1024
        volumes:
            - ./files/mysql/conf:/etc/mysql
            - ./files/mysql/data:/var/lib/mysql
        tty: true
        stdin_open: true
    redis:
        build: redis
        environment:
            - TIMEZONE=UTC
            - REDIS_PORT=1027
        ports:
            - 127.0.0.1:1027:1027
        volumes:
            - ./files/redis/conf:/etc/redis
            - ./files/redis/log:/var/log/redis
            - ./files/redis/data:/var/lib/redis
            - /var/www:/var/www
        tty: true
        stdin_open: true
    node:
        build: node
        environment:
            - TIMEZONE=UTC
        volumes: 
            - /var/www:/var/www
        depends_on:
            - mysql
            - redis
        tty: true
        stdin_open: true